services:
  - type: web
    name: restaurante-app
    runtime: node
    rootDir: .
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurante-db
          property: connectionString
      - key: PGSSLMODE
        value: require
    healthCheckPath: /health

databases:
  - name: restaurante-db
    plan: free
